# Generated by Django 4.0.6 on 2022-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(max_length=255)),
                ('house_number', models.TextField(max_length=20)),
                ('road', models.TextField(max_length=255)),
                ('postcode', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=255)),
                ('state', models.TextField(max_length=255)),
                ('country', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['contact_name'],
            },
        ),
    ]
