# Generated by Django 4.0.6 on 2022-07-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.TextField(max_length=255)),
                ("road", models.TextField(max_length=255)),
                ("house_number", models.TextField(max_length=20)),
                ("postcode", models.TextField(blank=True, max_length=20)),
                ("city", models.TextField(blank=True, max_length=255)),
                ("state", models.TextField(blank=True, max_length=255)),
                ("country", models.TextField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["contact_name"],
            },
        ),
    ]
